Fix cluster_application_kill method
The recently introduced cluster_application_kill() method was erroneously
calling `self.put()` to issue the status change to `KILLED`.  This resulted
in an AttributeError exception:
```
''ResourceManager' object has no attribute 'put''
```
in client code.

The base class issues put calls, via its `update()` method.  Once updated,
application kill requests succeed.